print("Drawing and folding")
var myDeck = Deck(shuffled: true)
print(myDeck)
print()
let first = myDeck.draw()
let second = myDeck.draw()
print("First card drawn: ", first!)
print("Second card drawn: ", second!)
print("Folding ", first!)
myDeck.fold(c: first!)
print("Outs contains: ", myDeck.outs)
print("Disards contains: ", myDeck.disards)
